language: clojure

env:
  global:
     - GH_REF=github.com/hscells/hscells.github.io.git
     - GH_TOKEN=Fpeeu+1rcuMlTEMwXSEpR8cJgozR9jcRE4Z+4bI7cOcbildbPEbDWgAXeQy0BDjzkiFHHRjJSahwzBt0vpXWUsYRaoNOZcZVs3aVvp5WLNMN/GOava+nsWlZkynTHUPAqIrt5UCCN+Gn5u62ADeEcakiC5HUMc39df8EXxJ6ZFcFWiF/vDIQkVI2VThO9f+vLJIFL/GJCWykabZuYti+iT0DONeLJEmOY8bdKLYW+iva9qo9JNOiM/s2q5yNr00JdlwcYl81rh3AhCRS2wZv1cLm2Job6RtQmlWbLRfXs24L6Jhy0WkZoFP1Yr/q27v+RXB/w8nFKgsJ6KEaw+hOdYl/BM/0MU2381WvW6zr/0x1Voz4uhw3atCGjMv3U5SJtaaMWKsFevRKCh9iuISB4jr+TO6GWAsPIsAv8P5xaUZcYLIObDj6WKZTKbajdYLGkIBMi3VPp5DkeDFOvd3/IHVyC6XbKVyAigyhPiSDUb7lTydP8cDKFtLvC7nXLq2358iE2nvwHZpCvLVVnzWV0ibWEf86tvwxIxNlOKNJJcGSs/FUbKI6ccGpDYPtTRgkniQnjzz43QY6IMfoh0HHCI50sxlW+tzjK5d/mUlfIUlrq9R8jCdEQxwdXDIxKaJgUS4ZRoP8NPAreFP7MyUCjiDdDHMXCToNnm2/BFVz0E0=
     - secure=Fpeeu+1rcuMlTEMwXSEpR8cJgozR9jcRE4Z+4bI7cOcbildbPEbDWgAXeQy0BDjzkiFHHRjJSahwzBt0vpXWUsYRaoNOZcZVs3aVvp5WLNMN/GOava+nsWlZkynTHUPAqIrt5UCCN+Gn5u62ADeEcakiC5HUMc39df8EXxJ6ZFcFWiF/vDIQkVI2VThO9f+vLJIFL/GJCWykabZuYti+iT0DONeLJEmOY8bdKLYW+iva9qo9JNOiM/s2q5yNr00JdlwcYl81rh3AhCRS2wZv1cLm2Job6RtQmlWbLRfXs24L6Jhy0WkZoFP1Yr/q27v+RXB/w8nFKgsJ6KEaw+hOdYl/BM/0MU2381WvW6zr/0x1Voz4uhw3atCGjMv3U5SJtaaMWKsFevRKCh9iuISB4jr+TO6GWAsPIsAv8P5xaUZcYLIObDj6WKZTKbajdYLGkIBMi3VPp5DkeDFOvd3/IHVyC6XbKVyAigyhPiSDUb7lTydP8cDKFtLvC7nXLq2358iE2nvwHZpCvLVVnzWV0ibWEf86tvwxIxNlOKNJJcGSs/FUbKI6ccGpDYPtTRgkniQnjzz43QY6IMfoh0HHCI50sxlW+tzjK5d/mUlfIUlrq9R8jCdEQxwdXDIxKaJgUS4ZRoP8NPAreFP7MyUCjiDdDHMXCToNnm2/BFVz0E0=

before_script:
 - git config --global user.email "harryscells@gmail.com"
 - git config --global user.name "Travis-CI"
 - git config --global push.default matching

after_script:
 - git clone https://github.com/hscells/hscells.github.io.git
 - lein doc
 - cd hscells.github.io
 - git add *
 - git commit -m "updated k-means javadoc"
 - git push --force "https://${GH_TOKEN}@${GH_REF}"
 - cd ../
 - lein uberjar

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: target/uberjar/k-means-0.7-standalone.jar
  skip_cleanup: true
  on:
    tags: true
